version: "3"
services:  
  org-sample_service-eth:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL=jdbc:mysql://<mysql_container_name>:<mysql_container_port>/<mysql_database_name>
      - MYSQL_USERNAME=<mysql_username>
      - MYSQL_PASSWORD=<mysql_password>
      - MONGODB_URL=mongodb://<mongodb_container_name>:<mongo_container_port>/<mongo_database_name>
      - MONGODB_USERNAME=<mongodb_username>
      - MONGODB_PASSWORD=<mongodb_password>